project:
  type: default
date: last-modified

format:
  html:
    toc: true
    number-sections: true
    format-links: false
    page-layout: full
    code-fold: true
    html-math-method: mathjax
    bibliography: ref.bib
    link-citations: true
    include-in-header:
      text: |
        <style>
        main { text-align: justify; hyphens: auto; }
        h1, h2, h3, h4, h5, h6 { text-align: left}
        </style>       
execute:
  echo: true
  warning: false
  message: false
  cache: false
  freeze: false
  # This tells Quarto to look for data/files in the same folder as the .qmd
  execute-dir: file

crossref:
  eq-prefix: "Eq."

# If ref.bib is one level up (with this YAML), use ../ref.bib
# If it's in the same folder as the .qmd, leave it as ref.bib
