---
title: "Building and Installing Package"
author: "Longhai Li"
format: html
editor_options: 
  chunk_output_type: console
execute: 
  dir: project
---

```{r setup, include=FALSE}
# This forces knitr to use the Project Root directory
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


# Rebuild .Rbuildignore (The "Strict Allow-List" Strategy)

```{r}
# ==============================================================================
# 2. DYNAMIC .Rbuildignore (The "Strict Allow-List" Strategy)
# ==============================================================================

### A. Top-Level Filter
allowed_top <- c(
  "DESCRIPTION", "NAMESPACE", "R", "man", "inst", "vignettes", 
  "data", "tests", "src", "README.md", "NEWS.md", "LICENSE"
)

all_top_items <- setdiff(list.files(all.files = TRUE, include.dirs = TRUE), c(".", ".."))
top_to_ignore <- setdiff(all_top_items, allowed_top)

# Format for .Rbuildignore
ignore_patterns <- paste0("^", gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\\1", top_to_ignore), "$")


### B. Vignettes Filter (Allow ONLY get-started.Rmd)
if (dir.exists("vignettes")) {
  vig_items <- setdiff(list.files("vignettes", all.files = TRUE, include.dirs = TRUE), c(".", ".."))
  
  # Regex to keep ONLY get-started.Rmd (case-insensitive for the extension)
  is_valid_vig <- grepl("^get-started\\.[qRr]md$", vig_items)
  vig_to_ignore <- vig_items[!is_valid_vig]
  
  if (length(vig_to_ignore) > 0) {
    vig_patterns <- paste0("^vignettes/", gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\\1", vig_to_ignore), "$")
    # Add these to our global ignore list
    ignore_patterns <- c(ignore_patterns, vig_patterns)
  }
}


### C. R Directory Filter (Allow ONLY .R or .r files)
if (dir.exists("R")) {
  r_items <- setdiff(list.files("R", all.files = TRUE, include.dirs = TRUE), c(".", ".."))
  
  # Regex to keep ONLY files ending in .R or .r
  is_valid_r <- grepl("\\.[Rr]$", r_items)
  r_to_ignore <- r_items[!is_valid_r]
  
  if (length(r_to_ignore) > 0) {
    r_patterns <- paste0("^R/", gsub("([.|()\\^{}+$*?]|\\[|\\])", "\\\\\\1", r_to_ignore), "$")
    # Add these to our global ignore list
    ignore_patterns <- c(ignore_patterns, r_patterns)
  }
}


# Write the final strict .Rbuildignore
writeLines(ignore_patterns, ".Rbuildignore")

```


# Reload the package

```{r}
library(renv)

devtools::document()
devtools::load_all() # reloading updated documents to current R session

remove.packages("Zresidual")
renv::install(".", prompt = FALSE)
```


# Build the package site on Github

## Build the whole Site
```{r}
#| eval: false
#devtools::document()
pkgdown::clean_site()
unlink("docs", recursive = TRUE)
# 3. Build fresh
pkgdown::build_site(
    lazy=TRUE,
    preview=TRUE,
    devel=TRUE, 
    install=FALSE)
```

## Build Specific Site Pages

### Build home page only
```{r}
#| eval: false
pkgdown::build_home()
```


### Build news only
```{r}
#| eval: false
pkgdown::build_news()
```

### Build an article

```{r}
#| eval: false
pkgdown::build_article("get-started")
```

```{r}
#| eval: false
pkgdown::build_article("demo_coxph_survival")
```


```{r}
#| eval: false
pkgdown::build_favicons()
```


```{r}
#| eval: false
pkgdown::preview_site()
```
